apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkis
  namespace: linkis
automountServiceAccountToken: false

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkis
  namespace: linkis
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "deployments", "replicasets", "statefulsets", "daemonsets", "namespaces"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkis
  namespace: linkis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkis
subjects:
- kind: ServiceAccount
  name: linkis
